UPDATE surveys SET name = 'BIO After Term Survey 2017 Fall' WHERE survey_id = 1;
UPDATE surveys SET name = 'HIS Early Term Survey 2017 Fall' WHERE survey_id = 2;
UPDATE surveys SET name = 'BIO Early Term Survey 2018 Summer Term 1' WHERE survey_id = 3;
UPDATE surveys SET name = 'HIS Late Term Survey 2017 Summer Term 1' WHERE survey_id = 4;
UPDATE surveys SET name = 'BIO Late Term Survey 2018 Summer Term 2' WHERE survey_id = 5;
UPDATE surveys SET name = 'BIO Early Term Survey 2017 Summer Term 2' WHERE survey_id = 6;
UPDATE surveys SET name = 'BIO After Term Survey 2018 Summer Term 1' WHERE survey_id = 7;
UPDATE surveys SET name = 'MAT After Term Survey 2018 Summer Term 1' WHERE survey_id = 8;
UPDATE surveys SET name = 'PSY Late Term Survey 2017 Summer Term 1' WHERE survey_id = 9;
UPDATE surveys SET name = 'BIO Late Term Survey 2017 Winter' WHERE survey_id = 10;
UPDATE surveys SET name = 'PSY Late Term Survey 2017 Fall' WHERE survey_id = 11;
UPDATE surveys SET name = 'MAT Early Term Survey 2018 Winter' WHERE survey_id = 12;
UPDATE surveys SET name = 'PSY Late Term Survey 2017 Fall' WHERE survey_id = 13;
UPDATE surveys SET name = 'PSY Early Term Survey 2017 Summer Term 2' WHERE survey_id = 14;
UPDATE surveys SET name = 'BIO Early Term Survey 2018 Summer Term 1' WHERE survey_id = 15;
UPDATE surveys SET name = 'MAT After Term Survey 2017 Fall' WHERE survey_id = 16;
UPDATE surveys SET name = 'CSC After Term Survey 2018 Summer Term 2' WHERE survey_id = 17;
UPDATE surveys SET name = 'MAT Late Term Survey 2018 Summer Term 1' WHERE survey_id = 18;
UPDATE surveys SET name = 'MAT Early Term Survey 2017 Summer Term 1' WHERE survey_id = 19;
UPDATE surveys SET name = 'HIS After Term Survey 2017 Summer Term 2' WHERE survey_id = 20;
UPDATE surveys SET name = 'CSC Late Term Survey 2017 Summer Term 2' WHERE survey_id = 21;
UPDATE surveys SET name = 'BIO Late Term Survey 2018 Summer Term 2' WHERE survey_id = 22;
UPDATE surveys SET name = 'MAT After Term Survey 2017 Summer Term 1' WHERE survey_id = 23;
UPDATE surveys SET name = 'PSY Early Term Survey 2018 Fall' WHERE survey_id = 24;
UPDATE surveys SET name = 'MAT Late Term Survey 2018 Summer Term 1' WHERE survey_id = 25;
UPDATE surveys SET name = 'MAT After Term Survey 2018 Summer Term 1' WHERE survey_id = 26;
UPDATE surveys SET name = 'CSC Early Term Survey 2018 Fall' WHERE survey_id = 27;
UPDATE surveys SET name = 'CSC After Term Survey 2017 Summer Term 1' WHERE survey_id = 28;
UPDATE surveys SET name = 'HIS Late Term Survey 2018 Summer Term 1' WHERE survey_id = 29;
UPDATE surveys SET name = 'MAT Early Term Survey 2018 Summer Term 2' WHERE survey_id = 30;
UPDATE surveys SET name = 'PSY After Term Survey 2017 Summer Term 2' WHERE survey_id = 31;
UPDATE surveys SET name = 'HIS Early Term Survey 2018 Summer Term 2' WHERE survey_id = 32;
UPDATE surveys SET name = 'PSY Early Term Survey 2018 Winter' WHERE survey_id = 33;
UPDATE surveys SET name = 'PSY After Term Survey 2018 Summer Term 2' WHERE survey_id = 34;
UPDATE surveys SET name = 'PSY After Term Survey 2018 Fall' WHERE survey_id = 35;
UPDATE surveys SET name = 'MAT After Term Survey 2018 Fall' WHERE survey_id = 36;
UPDATE surveys SET name = 'CSC Late Term Survey 2018 Summer Term 1' WHERE survey_id = 37;
UPDATE surveys SET name = 'HIS Late Term Survey 2018 Winter' WHERE survey_id = 38;
UPDATE surveys SET name = 'BIO Early Term Survey 2018 Winter' WHERE survey_id = 39;
UPDATE surveys SET name = 'PSY Late Term Survey 2017 Summer Term 1' WHERE survey_id = 40;
UPDATE surveys SET name = 'HIS After Term Survey 2018 Fall' WHERE survey_id = 41;
UPDATE surveys SET name = 'BIO After Term Survey 2018 Summer Term 2' WHERE survey_id = 42;
UPDATE surveys SET name = 'MAT After Term Survey 2017 Winter' WHERE survey_id = 43;
UPDATE surveys SET name = 'BIO After Term Survey 2017 Summer Term 2' WHERE survey_id = 44;
UPDATE surveys SET name = 'MAT After Term Survey 2018 Summer Term 2' WHERE survey_id = 45;
UPDATE surveys SET name = 'HIS Late Term Survey 2018 Summer Term 1' WHERE survey_id = 46;
UPDATE surveys SET name = 'CSC Early Term Survey 2018 Summer Term 2' WHERE survey_id = 47;
UPDATE surveys SET name = 'PSY Late Term Survey 2017 Summer Term 2' WHERE survey_id = 48;
UPDATE surveys SET name = 'BIO Late Term Survey 2017 Summer Term 2' WHERE survey_id = 49;
UPDATE surveys SET name = 'PSY Early Term Survey 2017 Summer Term 1' WHERE survey_id = 50;
UPDATE surveys SET name = 'MAT Early Term Survey 2018 Fall' WHERE survey_id = 51;
UPDATE surveys SET name = 'HIS Late Term Survey 2018 Summer Term 2' WHERE survey_id = 52;
UPDATE surveys SET name = 'CSC After Term Survey 2018 Summer Term 1' WHERE survey_id = 53;
UPDATE surveys SET name = 'CSC Early Term Survey 2017 Summer Term 2' WHERE survey_id = 54;
UPDATE surveys SET name = 'MAT After Term Survey 2017 Summer Term 2' WHERE survey_id = 55;
UPDATE surveys SET name = 'CSC Early Term Survey 2017 Fall' WHERE survey_id = 56;
UPDATE surveys SET name = 'BIO After Term Survey 2017 Winter' WHERE survey_id = 57;
UPDATE surveys SET name = 'MAT After Term Survey 2018 Summer Term 2' WHERE survey_id = 58;
UPDATE surveys SET name = 'CSC After Term Survey 2017 Summer Term 1' WHERE survey_id = 59;
UPDATE surveys SET name = 'CSC Early Term Survey 2018 Winter' WHERE survey_id = 60;
UPDATE surveys SET name = 'MAT After Term Survey 2018 Summer Term 2' WHERE survey_id = 61;
UPDATE surveys SET name = 'HIS Early Term Survey 2018 Summer Term 1' WHERE survey_id = 62;
UPDATE surveys SET name = 'HIS Late Term Survey 2018 Fall' WHERE survey_id = 63;
UPDATE surveys SET name = 'CSC After Term Survey 2018 Winter' WHERE survey_id = 64;
UPDATE surveys SET name = 'BIO After Term Survey 2018 Winter' WHERE survey_id = 65;
UPDATE surveys SET name = 'PSY After Term Survey 2018 Summer Term 1' WHERE survey_id = 66;
UPDATE surveys SET name = 'MAT Early Term Survey 2018 Winter' WHERE survey_id = 67;
UPDATE surveys SET name = 'PSY After Term Survey 2018 Summer Term 2' WHERE survey_id = 68;
UPDATE surveys SET name = 'PSY Early Term Survey 2018 Winter' WHERE survey_id = 69;
UPDATE surveys SET name = 'PSY After Term Survey 2018 Winter' WHERE survey_id = 70;
UPDATE surveys SET name = 'BIO Early Term Survey 2017 Summer Term 1' WHERE survey_id = 71;
UPDATE surveys SET name = 'CSC Late Term Survey 2018 Summer Term 1' WHERE survey_id = 72;
UPDATE surveys SET name = 'BIO Late Term Survey 2017 Fall' WHERE survey_id = 73;
UPDATE surveys SET name = 'HIS After Term Survey 2018 Winter' WHERE survey_id = 74;
UPDATE surveys SET name = 'HIS Early Term Survey 2018 Summer Term 1' WHERE survey_id = 75;
UPDATE surveys SET name = 'CSC Early Term Survey 2017 Summer Term 1' WHERE survey_id = 76;
UPDATE surveys SET name = 'BIO After Term Survey 2018 Summer Term 2' WHERE survey_id = 77;
UPDATE surveys SET name = 'MAT Late Term Survey 2018 Summer Term 2' WHERE survey_id = 78;
UPDATE surveys SET name = 'PSY Early Term Survey 2018 Winter' WHERE survey_id = 79;
UPDATE surveys SET name = 'CSC Late Term Survey 2018 Fall' WHERE survey_id = 80;
UPDATE surveys SET name = 'CSC Late Term Survey 2018 Winter' WHERE survey_id = 81;
UPDATE surveys SET name = 'BIO Early Term Survey 2017 Summer Term 1' WHERE survey_id = 82;
UPDATE surveys SET name = 'HIS Late Term Survey 2017 Summer Term 1' WHERE survey_id = 83;
UPDATE surveys SET name = 'MAT Early Term Survey 2017 Winter' WHERE survey_id = 84;
UPDATE surveys SET name = 'MAT After Term Survey 2017 Fall' WHERE survey_id = 85;
UPDATE surveys SET name = 'MAT Late Term Survey 2017 Winter' WHERE survey_id = 86;
UPDATE surveys SET name = 'PSY Late Term Survey 2017 Fall' WHERE survey_id = 87;
UPDATE surveys SET name = 'HIS After Term Survey 2018 Summer Term 1' WHERE survey_id = 88;
UPDATE surveys SET name = 'BIO After Term Survey 2017 Fall' WHERE survey_id = 89;
UPDATE surveys SET name = 'HIS Early Term Survey 2017 Summer Term 1' WHERE survey_id = 90;
UPDATE surveys SET name = 'HIS Early Term Survey 2017 Fall' WHERE survey_id = 91;
UPDATE surveys SET name = 'PSY After Term Survey 2017 Summer Term 2' WHERE survey_id = 92;
UPDATE surveys SET name = 'MAT After Term Survey 2017 Fall' WHERE survey_id = 93;
UPDATE surveys SET name = 'HIS After Term Survey 2017 Winter' WHERE survey_id = 94;
UPDATE surveys SET name = 'PSY Early Term Survey 2017 Fall' WHERE survey_id = 95;
UPDATE surveys SET name = 'CSC Late Term Survey 2018 Summer Term 1' WHERE survey_id = 96;
UPDATE surveys SET name = 'CSC Late Term Survey 2018 Fall' WHERE survey_id = 97;
UPDATE surveys SET name = 'MAT Early Term Survey 2017 Winter' WHERE survey_id = 98;
UPDATE surveys SET name = 'BIO Late Term Survey 2017 Winter' WHERE survey_id = 99;
UPDATE surveys SET name = 'PSY Late Term Survey 2018 Winter' WHERE survey_id = 100;
UPDATE surveys SET name = 'MAT After Term Survey 2017 Fall' WHERE survey_id = 101;
UPDATE surveys SET name = 'CSC After Term Survey 2018 Winter' WHERE survey_id = 102;
UPDATE surveys SET name = 'MAT After Term Survey 2018 Winter' WHERE survey_id = 103;
UPDATE surveys SET name = 'CSC Late Term Survey 2017 Winter' WHERE survey_id = 104;
UPDATE surveys SET name = 'BIO Late Term Survey 2018 Summer Term 2' WHERE survey_id = 105;
UPDATE surveys SET name = 'MAT After Term Survey 2018 Summer Term 1' WHERE survey_id = 106;
UPDATE surveys SET name = 'CSC Late Term Survey 2017 Winter' WHERE survey_id = 107;
UPDATE surveys SET name = 'CSC After Term Survey 2018 Summer Term 2' WHERE survey_id = 108;

